---
title: "Commandes LDA"
output: html_notebook
---


```{r}
donnees <- read.table("~/Dropbox/Rpourlastatetladatascience/donnees/ronfle.txt",header=T)
summary(donnees)
```

```{r}
library(MASS)
mod.complet <- lda(ronfle~.,data=donnees)
mod.complet
```

```{r}
plot(mod.complet)
```

```{r}
mat.X <- model.matrix(ronfle~.,data=donnees)[,-1]
head(mat.X)
```

```{r}
ronfle <- donnees$ronfle
library(klaR)
set.seed(1234)
sel <- stepclass(mat.X,ronfle,method="lda",direction="both",maxvar=6)
sel$model
```

```{r}
mod.sel <- lda(sel$formula,data=donnees)
mod.sel
```


```{r}
prev.complet <- lda(ronfle~.,data=donnees,CV=TRUE)$class
prev.sel <- lda(sel$formula,data=donnees,CV=TRUE)$class
```


```{r}
table(prev.complet,donnees$ronfle)
table(prev.sel,donnees$ronfle)
```

```{r}
mean(prev.complet!=donnees$ronfle)
mean(prev.sel!=donnees$ronfle)
```


```{r}
n_don1 <- matrix(c(42,55,169,0,58,94,185,4,35,70,180,6,67,63,166,3),ncol=4,byrow=T)
n_don2 <- matrix(c("F","N","H","O","H","O","F","N"),ncol=2,byrow=T)
n_donnees <- cbind.data.frame(n_don1,n_don2)
names(n_donnees) <- names(donnees)[-6]
predict(mod.sel,newdata=n_donnees)

```



```{r}
library(klaR)
stepclass(ronfle~.,data=donnees,method="lda",direction="both",improvement=0.1)
```

```{r}
library(caret)
slda <- train(ronfle ~ ., data = donnees,method = "stepLDA",trControl = trainControl(method = "cv"))
```

```{r}
gr <- data.frame(maxvar=1:6,direction="backward")
bb <- train(ronfle ~ ., data = donnees,method = "stepLDA",trControl = trainControl(method = "cv"),tuneGrid = gr)
bb1 <- stepclass(ronfle~.,data=donnees,method="lda",direction="backward",maxvar=2,criterion="AC")

```

```{r}
mat.X <- model.matrix(ronfle~.,data=donnees)[,-1]
set.seed(1234)
ronfle <- donnees$ronfle
bb2 <- stepclass(mat.X,ronfle,method="lda",direction="both",maxvar=6)

```

