---
title: "Analyse des Correspondances Multiples"
author: "Husson et al."
date: "05/09/2018"
output:
  html_document:
    toc: true
    toc_float: true 
---

# 1. Importer les données

```{r}
credit <- read.table("https://r-stat-sc-donnees.github.io/credit.csv", sep = ";", header=TRUE)
summary(credit)
```

```{r}
credit[,"Age"] <- factor(credit[,"Age"])
```

```{r, eval = FALSE}
for (i in 1:ncol(credit)){ # permet d’avoir les graphes un à un
  par(ask=TRUE) # cliquer sur la fenêtre graphique
  plot(credit[,i])  # pour voir le graphe
} 
```

```{r, echo = FALSE}
plot(credit[,"Marche"])
```

```{r}
levels(credit[,"Marche"])[5] <- "Moto"
```

# 2. Choisir les variables et les individus actifs

```{r,message=FALSE,warning=FALSE}
library(FactoMineR)
res.mca <- MCA(credit, quali.sup = 6:11, level.ventil = 0)
```

# 4. Choisir le nombre d’axes

```{r,fig.width=6,fig.height=5}
barplot(res.mca$eig[,2],names  =paste("Dim", 1:nrow(res.mca$eig)))
```

# 4. Analyser les résultats

```{r,message=FALSE,warning=FALSE}
plot(res.mca, invisible = c("var","quali.sup"))
```

```{r,message=FALSE,warning=FALSE}
plot(res.mca, invisible = c("var","quali.sup"), habillage = "Marche")
plot(res.mca, invisible = c("var","quali.sup"), habillage = 1)
```


```{r,message=FALSE,warning=FALSE}
plot(res.mca, invisible ="ind",
  title="Graphe des modalités actives et illustratives")
```

```{r,message=FALSE,warning=FALSE}
summary(res.mca, nbelements = 2, ncp = 2, nb.dec = 2)
```

```{r,message=FALSE,warning=FALSE}
plot(res.mca, choix="var")
```

# 5. Décrire de façon automatique les principales dimensions de variabilité

```{r,message=FALSE,warning=FALSE}
dimdesc(res.mca)
```
# Factoshiny

```{r,message=FALSE,warning=FALSE, eval = FALSE}
library(Factoshiny)
res.shiny <- MCAshiny(credit)
```



