---
title: "Tests sur les proportions"
author: "Husson et al."
date: "05/09/2018"
output: html_document
---

# 3.4.1 

```{r}
lat <- -24.66
lon <- 176.9
zoom <- 4
```

```{r,message=FALSE,warning=FALSE}
library(ggmap)
MaCarte <- get_map(location=c(lon,lat),zoom=zoom)
```

```{r,message=FALSE,warning=FALSE}
ggmap(MaCarte)
```


```{r}
data(quakes)
```

```{r}
ggmap(MaCarte) +
  geom_point(data=quakes,aes(x=long,y=lat,colour=depth)) +
  scale_color_gradient(low="yellow2",high="red4")+ theme_void()
```
```{r}
bbox <- make_bbox(long,lat,data=quakes)
bbox
```

```{r}
MaCarteopt <- get_map(bbox)
ggmap(MaCarteopt)
```
```{r}
centre <- geocode("Pic de Rochebrune, Megeve, France")
centre
```

```{r}
CarteRochebrune <- get_map(centre, zoom=13)
ggmap(CarteRochebrune)
```

```{r}
library(leaflet)
m <- leaflet()
m <- addTiles(m)
print(m)
```

```{r}
m <- leaflet() %>% addTiles()
print(m)
```
```{r}
m <- leaflet() %>%
setView(lng=6.62,lat=45.85,zoom=13) %>% addTiles()
print(m)
```

```{r}
m <- leaflet(data=quakes) %>%
  setView(lng=176.9, lat=-24.66, zoom=4) %>% 
  addTiles()
```

```{r}
m %>% addCircles(~long, ~lat)
```
```{r}
pal <- colorNumeric(palette=c(low="yellow2",high="red4"),domain = quakes$depth)
```
```{r}
pal(quakes$depth[1:3])
```

```{r}
m %>% addTiles() %>% 
  addCircles(~long,~lat,popup=~mag,color=~pal(depth))
```
```{r}
sta.paris <- read.csv("https://r-stat-sc-donnees.github.io/velib_paris_01_09_18.csv",fileEncoding = "UTF8")
summary(sta.paris)
```

```{r}
leaflet(data = sta.paris) %>% addTiles() %>% 
  addCircleMarkers(~ lon, ~ lat,radius=8,stroke = FALSE, fillOpacity = 0.5,color="red")
```

```{r}
leaflet(data = sta.paris) %>% addTiles() %>% 
  addCircleMarkers(~ lon, ~ lat,radius=8,stroke = FALSE, 
                   fillOpacity = 0.5,color="red",
                   popup = ~ paste("<b>Vélos dispos: </b>",as.character(numBikesAvailable)))
```

```{r}
leaflet(data = sta.paris) %>% addTiles() %>% 
  addCircleMarkers(~ lon, ~ lat,radius=8,stroke = FALSE,
                   fillOpacity = 0.5,color="red",popup = ~ paste(as.character(name),
                                                "<br/>","<b> Vélos dispos: </b>",as.character(numBikesAvailable)))
```
```{r}
SV <- geocode("Stade Velodrome Marseille")
info <- paste(sep = "<br/>",
"<b><a href=’https://fr.wikipedia.org/wiki/Stade_Vélodrome’>
Stade Velodrome</a></b>", "Marseille")
leaflet() %>% addTiles() %>% addPopups(SV[1]$lon, SV[2]$lat,info,options = popupOptions(closeButton = FALSE))
```
```{r}
setwd("C:/Users/husson/Dropbox/Rpourlastatetladatascience/chapitre/cartes/DONNEES")
library(sf)
dpt <- read_sf("dpt")
```

