---
title: 'Chapitre 3 : Visualiser les données'
author: "Husson et al."
date: "09/09/2018"
output:
  html_notebook: 
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

```{r, echo=FALSE}
setwd("C:/Users/husson/Dropbox/Rpourlastatetladatascience/chapitre/cartes/DONNEES")
```
# 3.4 Construire des cartes

## 3.4.1 Carte statique dans R

```{r,message=FALSE,warning=FALSE}
lat <- -24.66
lon <- 176.9
zoom <- 4
library(ggmap)
MaCarte <- get_map(location=c(lon,lat),zoom=zoom)
ggmap(MaCarte)
```

```{r}
data(quakes)
ggmap(MaCarte) +
  geom_point(data=quakes,aes(x=long,y=lat,colour=depth)) +
  scale_color_gradient(low="yellow2",high="red4") + theme_void()
```
```{r}
bbox <- make_bbox(long,lat,data=quakes)
bbox
MaCarteopt <- get_map(bbox)
ggmap(MaCarteopt)
centre <- geocode("Pic de Rochebrune, Megeve, France")
centre
CarteRochebrune <- get_map(centre, zoom=13)
ggmap(CarteRochebrune)
```

## 3.4.2 Carte dans un navigateur

```{r,message=FALSE,warning=FALSE}
library(leaflet)
m <- leaflet()
m <- addTiles(m)
print(m)
```
```{r,include=FALSE}
m <- leaflet() %>% addTiles()
print(m)
```
```{r}
m <- leaflet() %>%
  setView(lng=6.62,lat=45.85,zoom=13) %>%
  addTiles()
print(m)
```
```{r}
m <- leaflet(data=quakes) %>%
  setView(lng=176.9, lat=-24.66, zoom=4) %>%
  addTiles()
m %>% addCircles(~long, ~lat)
pal <- colorNumeric(palette=c(low="yellow2",high="red4"), domain = quakes$depth)
pal(quakes$depth[1:3])
m %>% addTiles() %>%
  addCircles(~long,~lat,popup=~mag,color=~pal(depth))
```

```{r}
sta.paris <- read.csv("https://r-stat-sc-donnees.github.io/velib_paris_01_09_18.csv",encoding = "UTF-8")
summary(sta.paris)
```
```{r}
leaflet(data = sta.paris) %>% addTiles() %>%
  addCircleMarkers(~ lon, ~ lat,radius=8,stroke = FALSE, fillOpacity = 0.5,color="red")
```
```{r}
leaflet(data = sta.paris) %>% addTiles() %>%
  addCircleMarkers(~ lon, ~ lat,radius=8,stroke = FALSE,
fillOpacity = 0.5,color="red",popup = ~ paste("<b>
        Vélos dispos: </b>",as.character(numBikesAvailable)))
```
```{r}
leaflet(data = sta.paris) %>% addTiles() %>%
  addCircleMarkers(~ lon, ~ lat,radius=8,stroke = FALSE,
fillOpacity = 0.5,color="red",popup = ~ paste(as.character(name),
"<br/>","<b> Vélos dispos: </b>",as.character(numBikesAvailable)))
```
```{r}
SV <- geocode("Stade Velodrome Marseille")
info <- paste(sep = "<br/>", "<b><a href=’https://fr.wikipedia.org/wiki/Stade_Vélodrome’>
Stade Velodrome</a></b>", "Marseille")
leaflet() %>% addTiles() %>% addPopups(SV[1]$lon, SV[2]$lat,info,options = popupOptions(closeButton = FALSE))
```

## 3.4.3 Carte avec contours : le format shapefile

```{r,message=FALSE,warning=FALSE}
library(readr)
chomage <- read_delim("https://r-stat-sc-donnees.github.io/tauxchomage.csv",delim=";")
class(chomage)
```
```{r,message=FALSE,warning=FALSE}
library(sf)
dpt <- read_sf("C:/Users/husson/Dropbox/Rpourlastatetladatascience/chapitre/cartes/DONNEES/dpt")
class(dpt)
```
```{r,message=FALSE,warning=FALSE}
library(dplyr)
dpt2 <- inner_join(dpt,chomage,by="CODE_DEPT")
class(dpt2)
```

```{r,message=FALSE,warning=FALSE}
library(tidyr)
dpt3 <- dpt2 %>% select(A2006=TCHOMB1T06,A2011=TCHOMB1T11,geometry) %>%
  gather("Annee","TxChomage",-geometry)
class(dpt3)
```

```{r,message=FALSE,warning=FALSE}
library(ggplot2)
ggplot() + geom_sf(data = dpt3, aes(fill = TxChomage)) +
  facet_wrap(~Annee, nrow = 1) +
  scale_fill_gradient(low="white",high="brown")+theme_bw()
```

```{r,message=FALSE,warning=FALSE}
library(maps)
map("state")
```

```{r}
dp <- st_transform(dpt2, crs="+init=epsg:4326")
library(leaflet)
fr <- leaflet(data=dp) %>% setView(2.21,46.23,6) %>% addTiles()
pal <- colorNumeric(palette="inferno",domain = c(dp$TCHOMB1T06,dp$TCHOMB1T11))
frf <- fr %>% addPolygons(color=~pal(TCHOMB1T06),group ="2006") %>%
  addPolygons(color=~pal(TCHOMB1T11),group="2011")
frf %>% addLayersControl(overlayGroups = c("2006", "2011"), options=
                           layersControlOptions(collapsed = FALSE))
```

