---
title: "Deep learning"
author: "Husson et al."
date: "05/09/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

# 1. Importer les données

```{r,message=FALSE,warning=FALSE}
library(kernlab)
data(spam)
```

```{r,message=FALSE,warning=FALSE}
library(keras)
spamX <- as.matrix(spam[,-58])
spamY <- to_categorical(as.numeric(spam$type)-1, 2)
```

# 2. Construire un réseau et optimiser les paramètres

```{r,message=FALSE,warning=FALSE}
use_session_with_seed(42)
mod.1couche <- keras_model_sequential() %>%
  layer_dense(units=2, activation ="softmax")
```

```{r,message=FALSE,warning=FALSE}
mod.1couche %>% compile(loss = "categorical_crossentropy",
                        optimizer=optimizer_rmsprop(),metrics=c("accuracy"))
res1couche <- mod.1couche %>%
  fit(spamX,spamY,epochs=30,batch_size=64,validation_split=0.2)
```

```{r,message=FALSE,warning=FALSE}
plot(res1couche)
```

```{r}
predict(mod.1couche, spamX)[1:4,]
```

```{r,message=FALSE,warning=FALSE}
use_session_with_seed(23)
mod.2couche <- keras_model_sequential() %>%
  layer_dense(units=30, activation ="relu") %>%
  layer_dense(units=2, activation ="softmax")
```

```{r,message=FALSE,warning=FALSE}
mod.2couche %>% compile(loss = "categorical_crossentropy",
                        optimizer=optimizer_rmsprop(),metrics=c("accuracy"))
res2couche <- mod.2couche %>%
  fit(spamX,spamY,epochs=30,batch_size=64,validation_split=0.2)
```
```{r}
predict(mod.2couche, spamX)[1:4,]
```

```{r,message=FALSE,warning=FALSE}
use_session_with_seed(56)
library(caret)
caret_mlp <- train(type ~ . , data = spam,
                   method = "mlpKerasDecay",
                   tuneGrid = expand.grid(size = c(30, 45), lambda = 0,
                   batch_size = 128, lr = 0.001, rho = 0.9,
decay = 0, activation = c("relu", "tanh")),
epoch = 30)    
```

```{r,message=FALSE,warning=FALSE}
caret_mlp
```

```{r,message=FALSE,warning=FALSE}
predict(caret_mlp, newdata = spam[1:3,])
```


# 4. Prédire Y pour de nouveaux individus

```{r}
set.seed(5678)
perm <- sample(4601,3000)
appX <- spamX[perm,]
appY <- spamY[perm,]
testX <- spamX[-perm,]
testY <- spamY[-perm,]
```

```{r,message=FALSE,warning=FALSE}
use_session_with_seed(42)
mod.1couche <- keras_model_sequential() %>%
  layer_dense(units=2, activation ="softmax")
mod.1couche %>% compile(loss = "categorical_crossentropy",
                        optimizer=optimizer_rmsprop(),metrics=c("accuracy"))
res1couche <- mod.1couche %>%
  fit(appX,appY,epochs=30,batch_size=64,validation_split=0.2)

pred1 <- predict(mod.1couche, testX)
```

```{r,message=FALSE,warning=FALSE}
use_session_with_seed(23)
mod.2couche <- keras_model_sequential() %>%
  layer_dense(units=30, activation ="relu") %>%
  layer_dense(units=2, activation ="softmax")
mod.2couche %>% compile(loss = "categorical_crossentropy",
                        optimizer=optimizer_rmsprop(),metrics=c("accuracy"))
res2couche <- mod.2couche %>%
  fit(appX,appY,epochs=30,batch_size=64,validation_split=0.2)
pred2 <- predict(mod.2couche, testX)
```

```{r,message=FALSE,warning=FALSE}
use_session_with_seed(56)
library(caret)
caret_mlp <- train(type ~ . , data = spam[perm,],
                   method = "mlpKerasDecay",
                   tuneGrid = expand.grid(size = c(30, 45), lambda = 0,
                   batch_size = 128, lr = 0.001, rho = 0.9,
decay = 0, activation = c("relu", "tanh")),
epoch = 30)    
caret_mlp
pred3 <- predict(caret_mlp, newdata = spam[-perm,])
```

```{r}
mean(as.integer(pred1>0.5)!=testY)
mean(as.integer(pred2>0.5)!=testY)
pred3 <- predict(caret_mlp, newdata = spam[-perm,])
mean(as.integer((pred3!="spam"))!=testY)
```




